///*
// * MatchMaker Settings API
// * \"Match maker tool\"
// *
// * The version of the OpenAPI document: 0.0.1
// * Contact: email@gmail.com
// *
// * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
// * https://openapi-generator.tech
// * Do not edit the class manually.
// */
//
//
//package com.pruqa.matchmakerstartercontroller;
//
//import com.pruqa.matchmakerstartercontroller.generated.SettingsControllerApi;
//import com.pruqa.matchmakerstartercontroller.generated.invoker.ApiException;
//import com.pruqa.matchmakerstartercontroller.generated.model.*;
//import org.junit.Test;
//import org.junit.Ignore;
//
///**
// * API tests for SettingsControllerApi
// */
//@Ignore
//public class SettingsControllerApiTest {
//
//    private final SettingsControllerApi api = new SettingsControllerApi();
//
//
//    /**
//     * Add a game to the list
//     *
//     * This operation can be used to add a game to the system
//     *
//     * @throws ApiException
//     *          if the Api call fails
//     */
//    @Test
//    public void addGameUsingPOSTTest() throws ApiException {
//        String requestId = null;
//        String sessionId = null;
//        GameRequest gameRequest = null;
//        GameResponse response = api.addGameUsingPOST(requestId, sessionId, gameRequest);
//
//        // TODO: test validations
//    }
//
//    /**
//     * Recover the game Rules
//     *
//     * This operation can be used to recover the Game Rules
//     *
//     * @throws ApiException
//     *          if the Api call fails
//     */
//    @Test
//    public void getGameRulesUsingPOSTTest() throws ApiException {
//        String requestId = null;
//        String sessionId = null;
//        GameRulesRequest gameRulesRequest = null;
//        GameRulesResponse response = api.getGameRulesUsingPOST(requestId, sessionId, gameRulesRequest);
//
//        // TODO: test validations
//    }
//
//    /**
//     * Verify the company
//     *
//     * This operation can be used to verify the company and the game definition
//     *
//     * @throws ApiException
//     *          if the Api call fails
//     */
//    @Test
//    public void verifyCompanyUsingPOSTTest() throws ApiException {
//        String requestId = null;
//        String sessionId = null;
//        CompanyRequest companyRequest = null;
//        String response = api.verifyCompanyUsingPOST(requestId, sessionId, companyRequest);
//
//        // TODO: test validations
//    }
//
//}
